# Generated by Django 3.2.4 on 2023-07-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_born',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
