# Generated by Django 3.2.4 on 2023-07-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_quotes', '0003_author_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_born',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
    ]
